### PR TITLE
Fix EPERM and socket mismatch between selected and succeeded pairs when using bridge (Docker) interfaces.

### LINKED ISSUE #77: ICE Runtime Error
Elixir WebRTC crashes while establishing a connection between two `ex_webrtc` PeerConnections.
```
     ** (RuntimeError) Selected local candidate's socket is different than succeeded local candidate's socket. This should never happen as we check against symmetric response.
         (ex_ice 0.12.0) lib/ex_ice/priv/ice_agent.ex:2620: ExICE.Priv.ICEAgent.change_connection_state/2
         (ex_ice 0.12.0) lib/ex_ice/priv/ice_agent.ex:1439: ExICE.Priv.ICEAgent.do_handle_stun_message/5
         (ex_ice 0.12.0) lib/ex_ice/ice_agent.ex:438: ExICE.ICEAgent.handle_info/2
         (stdlib 6.2.2) gen_server.erl:2345: :gen_server.try_handle_info/3
         (stdlib 6.2.2) gen_server.erl:2433: :gen_server.handle_msg/6
         (stdlib 6.2.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
     Last message: {:udp, {:"$inet", :gen_udp_socket, {#PID<0.7221.0>, {:"$socket", #Reference<0.3233463475.3375235073.191565>}}}, {172, 17, 0, 1}, 51871, <<1, 1, 0, 44, 33, 18, 164, 66, 153, 197, 187, 244, 235, 119, 80, 77, 33, 12, 184, 89, 0, 32, 0, 8, 0, 1, 226, 66, 43, 19, 164, 168, 0, 8, 0, 20, 59, 35, 173, 111, 161, 156, 196, 103, 44, ...>>}
```

### PR DESCRIPTION
**Pull request by Karolk99**
Closes #77 #83

### CODE REVIEW

**Comment by Karolk99** [comment]
Potential fixes:
* only check if `valid?` attribute is true
* Don't change pair state to `:waiting/:in_progress` when trying to nominate a pair.

**Review by mickel8 — CHANGES_REQUESTED** [review]
Normally, I would give an approve but this time we MUST be very verbose in comments both in the main logic as well as in tests. We spent a lot of time trying to find out what's going on with eperm and how to solve it so it MUST be very well described in comments for future reference. Especially, if it turns out that we are wrong

**Comment by mickel8** [comment]
> The problem with the test test/integration/p2p_test.exs:10 also occurs on the master branch. After initial debugging, the problem occurs when:

Nice catch!! Let's move this to a separate PR

File: test/priv/ice_agent_test.exs [hunk 1]
```diff
@@ -1357,6 +1371,79 @@ defmodule ExICE.Priv.ICEAgentTest do
...
+
+      # 1. L opens socket on interface 1 (I1), port 5000 - first local candidate (LC1)
+      # 2. L opens socket on interface 2 (I2), port 5000 - second local candidate (LC2)
+      # 3. L sends a connection check from LC1 to RC1. Given LC1 operates via I1, which is a bridge interface, its source address is rewritten to I2
+      # 4. R perceives the request from L as originating from I2, port 5000, and responds successfully to I2, port 5000
+      # 5. This response arrives to the I1 port 5000. L notices that R recognized it as coming from I2, port 5000
+      # 6. L chooses to use LC1 and RC1 as the discovered pair because we know that I1 is a bridge interface.
+
+      # Note: If we were to use LC2 and RC1 as the discovered pair
+      # we would have different sockets between the succeeded and discovered pairs, which would cause a runtime error.
```
Comment (mickel8) [inline test/priv/ice_agent_test.exs:1389]: Just describe what the test aims to check. We have detailed description in the main logic
